config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'posts#index'
    resources :posts, except: :show
  end

  post "/graphql", to: "graphql#execute"
  resources :subscribers, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :body, presence: true

  belongs_to :post

  after_create :send_new_comment_email

  private
  def send_new_comment_email
    SendNewCommentEmailJob.perform_async(id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, :intro, presence: true
  validates :title, uniqueness: true

  has_many :comments, dependent: :destroy

  after_create :queue_email_notifications

  private

  def queue_email_notifications
    QueueNewPostEmailsJob.perform_async(id)
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  http_basic_authenticate_with name: 'admin', password: 'password'

  layout "admin"
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_posts_path, notice: "Post #{@post.title} has been successfully created."
    else
      render :new 
    end
  end

  def edit
  end

  def update
    @post.update_attributes(post_params)

    if @post.save
      redirect_to admin_posts_path, notice: "Post #{@post.title} has been successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to admin_posts_path, notice: "Post deleted"
    else
      render :index
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :intro, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      authorised: authorised?
    }
    result = Unit1Schema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def authorised?
    token = request.authorization[7, request.authorization.length]
    decoded_token = JWT.decode(token, OpenSSL::PKey::RSA.new(ENV.fetch('AUTH0_CERTIFICATE')).public_key, true, { algorithm: 'RS256' })
    decoded_token.first.fetch("exp") >= Time.now.to_i
  rescue
    false
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController 
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      respond_to do |format| 
        format.json { render json: @subscriber }
      end
    else
      respond_to do |format| 
        format.json { render json: @subscriber.errors }
      end
    end
  end

  private 

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def render_markdown(text)
    markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(escape_html: true), autolink: true, tables: true)
    markdown.render(text)
  end
end

app/helpers/nav_helper.rb
module NavHelper
  def nav_class
    'c-nav' if current_page?(root_path)
  end

  def nav_brand_class
    'c-nav__brand' if current_page?(root_path)
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state

    state
  end
end

app/views/admin/posts/_form.html.erb
<%= render 'shared/form_errors', record: @post %>
<%= form_for [:admin, @post] do |f| %>
 <div class="form-group">
  <%= f.label :title %><br/>
  <%= f.text_field :title, class: "form-control" %>
  </div>
   <div class="form-group">
  <%= f.label :intro %><br/>
  <%= f.text_area :intro, class: "form-control" %>
  </div>
   <div class="form-group">
  <%= f.label :body %><br/>
  <%= f.text_area :body, rows: 15,  class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/posts/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Posts', admin_posts_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Post</li>
  </ol>
</nav>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Posts</li>
  </ol>
</nav>
<% if @posts.exists? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th width="80%">Title</th>
        <th class="u-align-right">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to post.title, "http://my_domain/posts/#{post.id}" %>
          </td>
          <td class="u-align-right">
            <%= link_to edit_admin_post_path(post), data: { behavior: 'edit'} do %>
              <i class="fa fa-edit" style="color: orange"></i>
            <% end %>
            <%= link_to admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?', behavior: 'delete'} do %>
              <i class="fa fa-trash" style="color: red"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are currently no posts to display. Why not try <%= link_to 'adding', new_admin_post_path %> one?</p>
<% end %>

app/views/admin/posts/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Posts', admin_posts_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Add New Post</li>
  </ol>
</nav>
<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unit1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light c-nav">
      <%= link_to 'Unit 1', admin_root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Posts', admin_posts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add New Post', new_admin_post_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= render 'shared/flash'%>
      <%= yield %>
    </div>
    <footer class="c-footer">
      <div class="container">
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/form_errors', record: @post%>
<%= form_for @post do |f| %>
  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/>
  <%= f.label :intro %><br/>
  <%= f.text_area :intro %><br/>
  <%= f.label :body %><br/>
  <%= f.text_area :body %><br/>
  <%= f.submit %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if name == "notice" %>
    <div class="alert alert-success" role="alert">
      <%= msg %>
    </div>
  <% else %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_form_errors.html.erb
<% if record.errors.any? %>
  <% record.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
  <% end %>
<% end %>